### ISSUE TITLE
Movie Details

### ISSUE THREAD

**Issue by jphill19** [jphill19/rancid-tomatillos-starter#7]
As a user, I can click a movie, and see that movie’s details.

- At minimum, I should see see a movie’s backdrop image, genres, and overview. You may choose to display more information if you’d like.
- When a movie’s details are displayed, none of the other movies will be visible, but the page’s header is still visible.
- When a movie’s details are displayed, the user should have a way to return to the main view of all movies (i.e. a home button). This button should not be visible if I am on the home page.

![Image](https://github.com/user-attachments/assets/f3844562-76bf-47ba-b5bf-5d12ff91eeec)

**Comment by marshallhotaling** [comment]
completed functionality for iteration 3 now just needs to be styled
